---
ansible_connection: local

jenkins_name: jenkins
sonarqube_name: sonarqube
hoverfly_name: hoverfly
app_name: springrest

jenkins:
  build:
    NAME: "{{ jenkins_name }}"
    SOURCE_REPOSITORY_URL: https://github.com/rht-labs/s2i-config-jenkins.git
    SOURCE_REPOSITORY_REF: v1.0
    BUILDER_IMAGE_STREAM_NAME: jenkins-2-rhel7
    BUILDER_IMAGE_STREAM_TAG_NAME: v3.10.14
    IMAGE_STREAM_NAMESPACE: "{{ ci_cd_namespace }}"
  deploy:
    NAMESPACE: "{{ ci_cd_namespace }}"
    JENKINS_IMAGE_STREAM_TAG: "{{ jenkins_name }}:latest"
    MEMORY_LIMIT: 2Gi
    JENKINS_OPTS: "--sessionTimeout=720"
    VOLUME_CAPACITY: 2Gi

sonarqube:
  build:
    NAME: "{{ sonarqube_name }}"
    SOURCE_REPOSITORY_URL: https://github.com/redhat-cop/containers-quickstarts.git
    SOURCE_REPOSITORY_REF: v1.4
    SOURCE_CONTEXT_DIR: sonarqube
  postgresql:
    POSTGRESQL_DATABASE: sonar
    VOLUME_CAPACITY: 5
    POSTGRESQL_PASSWORD: sonar
    POSTGRESQL_USER: sonar
  deploy:
    POSTGRES_DATABASE_NAME: "sonar"
    
app:
  build:
    APPLICATION_NAME: "{{ app_name }}"
    NAMESPACE: "{{ ci_cd_namespace }}"
    SOURCE_REPOSITORY_URL: https://github.com/roridedi/spring-rest.git
    SOURCE_REPOSITORY_REF: master
  deploy:
    NAMESPACE: "{{ ci_cd_namespace }}"
    APPLICATION_NAME: "{{ app_name }}"
    SA_NAMESPACE: "{{ ci_cd_namespace }}"
    READINESS_PATH: "/"
    READINESS_RESPONSE: "{}"
  
openshift_cluster_content:
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/master/jenkins/jenkins-ephemeral-template.yml"
    params_from_vars: "{{ jenkins.build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins
    - jenkins-build
  - name: sonarqube
    template: "https://raw.githubusercontent.com/roridedi/containers-quickstarts/v1.4/build-docker-generic/.openshift/templates/docker-build-template.yml"
    params_from_vars: "{{ sonarqube.build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - sonarqube
      - sonarqube-build
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slave-mvn
    template: "https://raw.githubusercontent.com/roridedi/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/mvn"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins-slaves
    - mvn-slave
    - maven
- object: ci-cd-deployments
  content:
  - name: sonarqube
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/sonarqube/sonarqube-deployment-template.yml"
    params_from_vars: "{{ sonarqube.deploy }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - sonarqube
      - sonarqube-deploy
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params_from_vars: "{{ sonarqube.postgresql }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - sonarqube
      - sonarqube-postgresql
      - sonarqube-postgresql-deploy
  - name: nexus
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/nexus/nexus-deployment-template.yml"
    params_from_vars:
      VOLUME_CAPACITY: 10Gi
      MEMORY_LIMIT: 2Gi
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - nexus
      - nexus-deploy
  - name: jenkins-ephemeral
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/jenkins/jenkins-ephemeral-template.yml"
    params_from_vars: "{{ jenkins.deploy }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - jenkins
      - jenkins-deploy
  - name: app-build
    template: "https://raw.githubusercontent.com/redhat-cop/container-pipelines/master/basic-spring-boot/.openshift/templates/build.yml"
    params_from_vars: "{{ app.build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - app
      - app-build
  - name: app-deploy
    template: "https://raw.githubusercontent.com/redhat-cop/container-pipelines/master/basic-spring-boot/.openshift/templates/deployment.yml"
    params_from_vars: "{{ app.deploy }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - app
      - app-deploy
  - name: app-deploy
    template: "https://raw.githubusercontent.com/redhat-cop/container-pipelines/master/basic-spring-boot/.openshift/templates/deployment.yml"
    params_from_vars: "{{ app.deploy }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - app
      - app-deploy
  - name: app-deploy
    template: "https://raw.githubusercontent.com/redhat-cop/container-pipelines/master/basic-spring-boot/.openshift/templates/deployment.yml"
    params: "{{ playbook_dir }}/params/app/deploy_dev"
    tags:
      - app
      - app-deploy
      - app-dev
  - name: app-deploy
    template: "https://raw.githubusercontent.com/redhat-cop/container-pipelines/master/basic-spring-boot/.openshift/templates/deployment.yml"
    params: "{{ playbook_dir }}/params/app/deploy_test"
    tags:
      - app
      - app-deploy
      - app-test
