---
ansible_connection: local

jenkins_name: jenkins
hoverfly_name: hoverfly
app_name: springrest

jenkins:
  build:
    NAME: "{{ jenkins_name }}"
    JENKINS_IMAGE_STREAM_TAG: "{{ jenkins_name }}:latest"
    MEMORY_LIMIT: 2Gi
    MEMORY_REQUEST: 2Gi
    JENKINS_OPTS: "--sessionTimeout=720"
    VOLUME_CAPACITY: 2Gi

app:
  build:
    APPLICATION_NAME: "{{ app_name }}"
    NAMESPACE: "{{ ci_cd_namespace }}"
    SOURCE_REPOSITORY_URL: https://github.com/roridedi/spring-petclinic.git
    SOURCE_REPOSITORY_REF: master
    CONTEXT_DIR: ""
  deploy:
    NAMESPACE: "{{ ci_cd_namespace }}"
    APPLICATION_NAME: "{{ app_name }}"
    SA_NAMESPACE: "{{ ci_cd_namespace }}"
    READINESS_PATH: "/"
    READINESS_RESPONSE: "{}"
  
openshift_cluster_content:
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "https://raw.githubusercontent.com/roridedi/openshift-templates/master/jenkins/jenkins-ephemeral-template.yml"
    params_from_vars: "{{ jenkins.build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins
    - jenkins-build
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slave-mvn
    template: "https://raw.githubusercontent.com/roridedi/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/mvn"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins-slaves
    - mvn-slave
    - maven
- object: ci-cd-deployments
  content:
  - name: nexus
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/nexus/nexus-deployment-template.yml"
    params_from_vars:
      VOLUME_CAPACITY: 10Gi
      MEMORY_LIMIT: 2Gi
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - nexus
      - nexus-deploy
  - name: app-build
    template: "https://raw.githubusercontent.com/redhat-cop/container-pipelines/master/basic-spring-boot/.openshift/templates/build.yml"
    params_from_vars: "{{ app.build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - app
      - app-build
  - name: app-deploy
    template: "https://raw.githubusercontent.com/roridedi/container-pipelines/master/basic-spring-boot/.openshift/templates/deployment.yml"
    params: "{{ playbook_dir }}/params/app/deploy_dev"
    tags:
      - app
      - app-deploy
      - app-dev
  - name: app-deploy
    template: "https://raw.githubusercontent.com/roridedi/container-pipelines/master/basic-spring-boot/.openshift/templates/deployment.yml"
    params: "{{ playbook_dir }}/params/app/deploy_test"
    tags:
      - app
      - app-deploy
      - app-test